### ISSUE TITLE
Handles

### ISSUE THREAD

**Issue by Fim1am** [cmacmillan/CurveDesigner#2] opened 2021-11-24 07:34 UTC
Hello! I  have gizmos handles anywhere but their place (Unity 2021.1.16f1)
![Screenshot_2](https://user-images.githubusercontent.com/20174316/143194515-5833d328-75d1-430d-8e1d-fde67aede3c9.png)
![Screenshot_3](https://user-images.githubusercontent.com/20174316/143194518-6e28ea06-af8f-433a-8cb3-82ab33823ed8.png)
![Screenshot_4](https://user-images.githubusercontent.com/20174316/143194519-fd426092-b4ff-4b7b-bce6-08573bcb119c.png)
![Screenshot_5](https://user-images.githubusercontent.com/20174316/143194521-a834b5e0-8eae-4db4-a931-6926c6ff0c1d.png)

**Comment by cmacmillan** [comment] 2021-11-24 19:51
That's not good. I'll try to reproduce this issue and let you know what I find.

**Comment by cmacmillan** [comment] 2021-11-25 21:54
So this appears to be an issue with having multiple scene views open at once. Currently only the most recent scene view has correctly positioned handles.

**Comment by LucaBGt** [comment] 2021-11-28 00:37
<img width="669" alt="Bildschirmfoto 2021-11-28 um 01 36 50" src="https://user-images.githubusercontent.com/32401333/143724523-bb608775-f2d0-4787-818b-8cbd56fa66e8.png">
Hi! I'm having the same issue with Unity 2020.3.5f1 on Mac.
I only have one Scene View open, though.
Thanks!

**Comment by cmacmillan** [comment] 2021-11-28 01:51
@LucaBGt alright I was actually able to reproduce this by changing my UI scale. 
![image](https://user-images.githubusercontent.com/10664877/143725907-7a73f9e0-fdcd-4909-ac03-56f029a9fcd2.png)

**Comment by LucaBGt** [comment] 2021-11-28 09:17
OK, so this option, for the UI Scaling still doesn't exist in the latest Mac Versions. It looks like my Unity's UI Scaling is stuck at 150% at the moment, and I can't change it until it updates.

**Comment by LucaBGt** [comment] 2021-11-28 09:22
After playing around with this https://github.com/usr-sse2/RDM/releases the scaling issue seems to originate from Apple's Retina displays.

**Comment by cmacmillan** [comment] 2021-11-28 21:34
Yeah I'll look into it and fix it so it works with all scaling settings.

**Comment by cmacmillan** [comment] 2021-11-29 08:21
Fixed by f23dd3c98bb09dc4f4e9de45bb9d8d0748f7d931

**Closed as completed by cmacmillan** 2021-11-29 08:21 UTC
Labels: bug
